window.journalPrompts = [
  "How do you feel right now, and what might be influencing your emotions?",
  "Write about something you’re proud of accomplishing.",
  "What’s one thing you want to improve about yourself?",
  "What makes you feel confident?",
  "What’s a lesson you’ve learned recently?",
  "What’s your favorite way to spend a day off?",
  "Write about your favorite book, movie, or song and why it resonates with you.",
  "What’s your favorite place in the world, and why?",
  "Describe your favorite meal or a food that brings you comfort.",
  "Who’s your favorite person to spend time with, and what do you love about them?",
  "Write about a childhood memory that makes you laugh.",
  "What was the best trip you’ve ever taken?",
  "Describe the last time you felt really peaceful.",
  "What’s something you’ve recently learned about your family history?",
  "Write about a tradition or holiday you love.",
  "What does kindness mean to you?",
  "What’s one value that’s most important in your life?",
  "Write about a time when you stood up for something you believed in.",
  "What does success mean to you?",
  "How do you show love to others?",
  "What sounds, sights, or smells are around you right now?",
  "Write about one thing you noticed today that you usually overlook.",
  "What’s your favorite time of day, and why?",
  "What does 'being present' mean to you?",
  "Write about something in nature that makes you feel calm.",
  "What’s the kindest thing someone has done for you recently?",
  "Write about a way you’ve helped someone else recently.",
  "What do you appreciate most about your closest friend?",
  "Who has had the biggest positive influence on your life?",
  "Write about someone you miss and why.",
  "What’s one habit you’d like to create or break?",
  "What’s a piece of advice you’ve been given that stuck with you?",
  "How do you handle change in your life?",
  "Write about something that scared you but you did it anyway.",
  "What’s one thing you’ve done this year that you’re proud of?",
  "Write about something you loved to do as a kid.",
  "If you could give advice to your younger self, what would you say?",
  "What’s a difficult moment from your past that you’ve overcome?",
  "Write about a teacher or mentor who inspired you.",
  "What’s a time when you felt really brave?",
  "What are you most excited about in the next month?",
  "Where do you see yourself in five years?",
  "Write about something new you’d like to try.",
  "What do you want to achieve by the end of this year?",
  "What are three things you hope to do in the next week?",
  "Write about three small things you’re grateful for at this exact moment.",
  "What’s one positive thought or affirmation you can carry with you today?",
  "Write about a recent experience where you felt truly connected to the world around you.",
  "Think of an object nearby—what does it feel like, smell like, and remind you of?",
  "What’s the last thing that made you laugh or smile? How did it feel?",
  "If you had no to-do list today, how would you spend your time?",
  "Describe the feeling of taking a deep breath—what sensations do you notice in your body?",
  "Reflect on your last meal. What did it taste like, and how did it make you feel?",
  "Write about a simple pleasure you experienced recently, like feeling the sun on your skin or hearing a favorite song.",
  "Imagine yourself walking in nature—what do you hear, smell, and feel?",
  "Write about a time when you felt completely at peace. What made it special?",
  "What’s one thing you want to let go of that no longer serves you?",
  "Write about one way you can simplify your life.",
  "What’s something you could do today to nourish your mind, body, or spirit?",
  "Write a list of your priorities—are they aligned with how you spend your time?",
  "How do I feel right now—physically, emotionally, and mentally?",
  "What’s one thing I can do today to take care of myself?",
  "What is draining my energy, and how can I address it?",
  "List three things I’ve done recently that made me feel good.",
  "What is one way I can be kinder to myself today?",
  "What does my body need right now—rest, movement, hydration, or something else?",
  "Reflect on how I’ve been sleeping—am I getting enough rest? How can I improve this?",
  "What is one nutritious meal or snack I can plan for today?",
  "How can I incorporate more movement into my day in a way that feels enjoyable?",
  "Write about a self-care ritual (like a warm bath or a skincare routine) that helps me feel refreshed.",
  "What has been weighing on my mind lately? How can I release or manage it?",
  "List three things that make me feel calm and grounded.",
  "What is one way I can express my emotions in a healthy way?",
  "Write about a recent challenge I faced and how I supported myself through it.",
  "What are some affirmations I can say to myself when I’m feeling overwhelmed?",
  "What’s one thing I’ve done recently that I’m proud of?",
  "What are three qualities I love about myself?",
  "Reflect on a time I felt confident or empowered. What contributed to that feeling?",
  "Write a letter of encouragement to my future self.",
  "What is something I’ve accomplished, big or small, that deserves celebration?",
  "What’s one thing I can say “no” to this week to protect my time and energy?",
  "Who or what in my life feels supportive, and who or what feels draining?",
  "Reflect on a time I prioritized someone else’s needs over my own—how did it make me feel?",
  "What are my current boundaries, and are they working for me?",
  "What is one way I can advocate for myself today?",
  "What does self-care mean to me personally?",
  "What’s a part of myself I’ve been neglecting, and how can I nurture it?",
  "Write about a place or memory that makes me feel peaceful.",
  "What are some signs I’m starting to feel burnt out? How can I prevent it?",
  "Reflect on a time I felt truly connected to myself—what contributed to that feeling?",
  "What is one self-care goal I’d like to achieve in the next month?",
  "How can I create more balance between work and rest?",
  "Write about a routine I could create to feel more grounded each day.",
  "What’s one thing I’d like to try to improve my well-being (e.g., therapy, meditation, journaling)?",
  "How can I prioritize my own needs without feeling guilty?",
  "What does the word “boundaries” mean to me?",
  "What are my non-negotiables in relationships, work, or other areas of my life?",
  "Reflect on a time when I felt someone crossed my boundaries. How did it make me feel?",
  "What are my biggest challenges when it comes to setting boundaries?",
  "How do I know when someone has crossed a boundary? What physical or emotional signs do I notice?",
  "How do I protect my emotional energy during stressful situations?",
  "Write about a time I felt drained because I didn’t set a boundary. What could I have done differently?",
  "Who in my life respects my emotional boundaries, and how do they show it?",
  "What’s one way I can communicate my feelings more effectively when my boundaries are crossed?",
  "How do I handle guilt when I say “no” to something or someone?",
  "Reflect on how I manage my time. Do I feel in control, or do I often feel overwhelmed?",
  "What’s one way I can carve out more personal time for myself this week?",
  "Write about a time someone respected my physical space. How did it make me feel?",
  "Are there areas in my life where I feel overcommitted? How can I address this?",
  "What does an ideal balance between work, relationships, and personal time look like for me?",
  "How comfortable am I expressing my boundaries to others? Why?",
  "Write about a time I successfully communicated a boundary. What helped me do it?",
  "What phrases or language can I use to set a boundary politely but firmly?",
  "Who do I find it most difficult to set boundaries with, and why?",
  "How can I handle situations where someone doesn’t respect my boundaries?",
];
